name: IDFPlus Build Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - build-workflow-testing

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python and enable cache
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            'requirements-dev.txt'
            'requirements.txt'

      - name: Install global dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Install debian-specific dependencies
        if: startswith(matrix.os, 'ubuntu')
        run: |
          sudo apt install -y debhelper

      - name: Freeze the app
        run: |
          python setup.py freeze

      - name: Harvest file names for wix
        if: startswith(matrix.os, 'win')
        run: |
          python setup.py harvest

      - name: Upload harvested file names
        if: startswith(matrix.os, 'win')
        uses: actions/upload-artifact@v3
        with:
          name: idfplus_harvest
          path: build/idfplus_harvest.wxs

      - name: Package the app
        run: |
          python setup.py make_installer

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.os}}
          path: artifacts
