name: IDFPlus Wix Harvest

on:
  workflow_dispatch:
  push:
    branches:
      - build-workflow-testing

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  harvest:

  runs-on: windows-2019
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python and enable cache
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: |
          'requirements-dev.txt'
          'requirements.txt'

      - name: Install global dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Freeze the app
        run: |
          python setup.py freeze

      - name: Harvest files for wixinstaller
        run: |
          python setup.py harvest

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: idfplus_harvest
          path: build/idfplus_harvest.wxs
